### PR TITLE
Text position and color

### PR DESCRIPTION
**Pull request by TekhnaeRaav**
I thought this might be a better position and color if you like it. The old positioning I think was a little strange because it was right where the player moves his hand and items which makes it harder to read, and the color I thought was maybe just unnecessary. I tried real quick to get the darkness on the white text right to minimize the color blending of the background and the text.

### CODE REVIEW

**Comment by mflink3012** [comment]
Hello @TekhnaeRaav!

I will test it.


Maybe it could be better to put some positions as suggestions to a settings-file.
So everyone can pick his favourite.

Greetings!

**Comment by mflink3012** [comment]
Ok. Tested it.
Problem is: Resizing the window/screen will move it to unreadable locations.

Default size in Debian Stretch: 800px*600px:
Default size in Debian Stretch: 800px*600px

My windowed fullscreen: 1674px*938px:
My windowed fullscreen: 1674px*938px

So we have to find a better solution.

**Comment by mflink3012** [comment]
grafik

This should be better. This is stable:
``...
        hud_elem_type = "text",
        position  = {x = 0.5, y = 1.0},
        offset    = {x = 100, y = -70},
        text      = "",
        alignment = 0,
        scale     = { x = 100, y = 30},
        number    = 0xcfcfcf,
...``

I put a screen with schematics to describe the new positioning:
grafik

**Comment by mflink3012** [comment]
Tests this with resizing shows stability.

BUT:
This could create problems with some mods (like hunger, armor, etc.) showing the text inside the other mods graphics.

I will put this position to a preset ``above_hotbar`` and implement code to define custom-settings.

**Comment by TekhnaeRaav** [comment]
Hi! Yes, oops I forgot to take into account the the life HUD..and the resize :disappointed:  . Anyway your resizing works :+1: . Oh, hunger stacks on top of life and armor doesn't have HUD, but we forgot bubbles!(breath) So the text will never be able to go there. So I just threw up the the changes that no HUD should interfere! Also, we may be able to have the text change position depending on if you have hunger mods, damage, or sprinting enabled to minimize player view obstruction. :thinking:

**Comment by TekhnaeRaav** [comment]
PS: This calls for a new screenshot. ;)

**Comment by mflink3012** [comment]
Hi @TekhnaeRaav !

I changed the code to enable presets and custom settings.

**Comment by mflink3012** [comment]
For

> but we forgot bubbles!(breath) 

I created issue #4

**Comment by mflink3012** [comment]
Hi @TekhnaeRaav !

I have done things by now.
You can reset and provide your style-presets (or other improvements/fixes), if you like.

Greetings!

**Pull request closed without merging**
